
DELETE http://localhost:3001/api/blogs HTTP/1.1

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFydG8iLCJpZCI6IjVjZWY4YTE1YjRlZTNiMmYxNmRiN2RjMyIsImlhdCI6MTU1OTI5MjExMn0.FZIoeLI3Xt5Znmnhabmarms6Bh8PblBVTOU-0iVsiy8

{
    "title": "Arto wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "§": 2
}